_("Othello");
_("&Game");
_("&Start");
_("Single &Machine Game\tCtrl+1");
_("Start a single machine game");
_("Game &Server\tCtrl+2");
_("Start a network game as server");
_("Game &Client\tCtrl+3");
_("Join a network game");
_("Select the type of game");
_("S&top\tCtrl+E");
_("Stop the game");
_("&Restart\tCtrl+R");
_("Restart the game");
_("&Players\tCtrl+P");
_("Config the players");
_("&Quit\tCtrl+Q");
_("Exit program");
_("&Settings");
_("Prefere&nce");
_("Configure program preference");
_("&Help");
_("&About");
_("About the program");
_("BLACK");
_("0");
_("0");
_(":");
_("0");
_("WHITE");
_("0");
_("Debug Messages");
_("Choose Player");
_("unknown");
_("VS");
_("unknown");
_("Player A");
_("Player B");
_("Available Players");
_("Player Infomation");
_("unknown");
_("Summary:");
_("unknown");
_("Description:");
_("unknown");
_("Arguments");
_("Add(&A)");
_("Delete(&D)");
_("Reset(&R)");
_("Preference");
_("Choose Language(*)");
_("Current Language:");
_("unknown");
_("Choose Theme(*)");
_("Current Theme:");
_("unknown");
_("Plugin Directories");
_("Add");
_("Remove");
_("Move Up");
_("Move Down");
_("Game Server Configuration");
_("Server TCP Port");
_("Game Speed");
_("100");
_("200");
_("300");
_("400");
_("500");
_("600");
_("700");
_("800");
_("*NOTE* : Settings marked with '*' need to restart program to take effect");
